language: php

services:
  - mysql

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: TYPO3_VERSION=^8 PHPUNIT=5.7.5
    - php: 7.0
      env: TYPO3_VERSION=^8 PHPUNIT=5.7.5

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - torben@derhansen.com

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms="$TYPO3_VERSION" phpunit/phpunit="$PHPUNIT"
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
  - >
    echo;
    .Build/bin/typo3cms install:setup --non-interactive --database-user-name="root" --database-host-name="127.0.0.1" --database-port="3306" --database-name="typo3" --site-setup-type="site" --admin-user-name="admin" --admin-password="password";
    .Build/bin/typo3cms extension:activate tstemplate codeception_test;
    # Start a local webserver on port 8888;
    php -S 127.0.0.1:8888 -t .Build/web >/dev/null 2>&1 &;
    .Build/bin/codecept run --steps;